const JobActionTypes = {
  GET_JOB_LIST_START: "GET_JOB_LIST_START",
  GET_JOB_LIST_SUCCESS: "GET_JOB_LIST_SUCCESS",
  GET_JOB_LIST_FAILED: "GET_JOB_LIST_FAILED",
  SET_ADD_NEW_JOB_DETAILS: "SET_ADD_NEW_JOB_DETAILS",
  ADD_NEW_JOB_SUCCESS: "ADD_NEW_JOB_SUCCESS",
  ADD_NEW_JOB_FAILED: "ADD_NEW_JOB_FAILED",
  DELETE_JOB: "DELETE_JOB",
  DELETE_JOB_SUCCESS: "DELETE_JOB_SUCCESS",
  DELETE_JOB_FAILED: "DELETE_JOB_FAILED",
  UPDATE_JOB_DETAILS: "UPDATE_JOB_DETAILS",
  UPDATE_JOB_DETAILS_SUCCESS: "UPDATE_JOB_DETAILS_SUCCESS",
  UPDATE_JOB_DETAILS_FAILED: "UPDATE_JOB_DETAILS_FAILED",
  UPDATE_API_RESPONSE: "UPDATE_API_RESPONSE",
};

export default JobActionTypes;
